version: "3.7"

services:
  app:
    build:
      context: .
      target: dev
    image: narutiga/todo-dev:latest
    container_name: todo-dev
    ports:
      - 8080:8080
    init: true
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
    # env_file:
    #   - .env.local
    command: sh -c "yarn prisma generate && yarn dev"

  test:
    build:
      context: .
      target: test
    image: narutiga/todo-test:latest
    container_name: todo-test
    ports:
      - 8090:8090
    init: true
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      # - node_modules:/app/node_modules
    command: sh -c "yarn prisma generate && yarn test"
# volumes:
#   node_modules:
