name: Unit Test

on: [push]

jobs:
  migrate-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: echo docker and compose version
        run: docker -v && docker compose -v
      - name: run migrate & test
        run: cat compose.yaml
