name: unit-test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: show compose.yaml file
        run: cat compose.yaml
#       - name: run migrate & test
#         run: docker-compose run test
