name: Unit Test

on: [push]

jobs:
  migrate-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: echo docker and compose version
        run: docker -v && docker compose -v
      - name: container clear
        run: docker rm $(docker ps -a -q)
      - name: image clear
        run: docker rmi $(docker images -q)
      - name: run migrate & test
        run: docker-compose run test
